# Generated by Django 2.1.7 on 2019-03-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0003_auto_20190314_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-date']},
        ),
    ]
